-- LEGENDAS
CREATE TABLE IF NOT EXISTS legendas (
  ID                   BIGSERIAL PRIMARY KEY,
  DATA_GERACAO         DATE,
  ANO_ELEICAO          INT,
  NUM_TURNO            INT,
  DESCRICAO_ELEICAO    TEXT,
  SIGLA_UF             TEXT,
  SIGLA_UE             TEXT,
  CODIGO_CARGO         INT,
  DESCRICAO_CARGO      TEXT,
  TIPO_LEGENDA         TEXT,
  NUMERO_PARTIDO       INT,
  SIGLA_PARTIDO        TEXT,
  NOME_PARTIDO         TEXT,
  SIGLA_COLIGACAO      TEXT,
  NOME_COLIGACAO       TEXT,
  COMPOSICAO_COLIGACAO TEXT,
  SEQUENCIAL_COLIGACAO NUMERIC
);